---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
  annotations:
    platform.confluent.io/zookeeper-myid-offset: "100"
spec:
  oneReplicaPerNode: true
  podTemplate:
   resources:
    limits:
      cpu: 1000m
      memory: 3G
    requests:
      cpu: 500m
      memory: 1024Mi
   tolerations:
    - effect: NoSchedule
      key: app
      value: confluent
   affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - confluent
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  configOverrides:
    server:
      - auto.create.topics.enable=false
      - num.partitions=12
      - allow.everyone.if.no.acl.found=true
  authorization:
    type: simple
  listeners:
    custom:
      - authentication:
          type: plain
          jaasConfig:
            secretRef: credential
        tls:
          enabled: false
        name: plaintext
        port: 9096
    external:
      externalAccess:
        type: staticForPortBasedRouting
        staticForPortBasedRouting:
          host: nft.kafka.alpha.local
          portOffset: 9094
  oneReplicaPerNode: true
  podTemplate:
   resources:
    limits:
      cpu: 1500m
      memory: 10G
    requests:
      cpu: 500m
      memory: 4096Mi
   tolerations:
    - effect: NoSchedule
      key: app
      value: confluent
   affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - confluent
  replicas: 4
  image:
    application: confluentinc/cp-server:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 250Gi
  metricReporter:
    enabled: true
---
 apiVersion: platform.confluent.io/v1beta1
 kind: Connect
 metadata:
   name: connect
   namespace: confluent
 spec:
  oneReplicaPerNode: true
  podTemplate:
   resources:
    limits:
      cpu: 1500m
      memory: 3G
    requests:
      cpu: 500m
      memory: 1G
   tolerations:
    - effect: NoSchedule
      key: app
      value: confluent
   affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - confluent
  replicas: 1
  image:
    application: ahbaenssdbpnpdacrtmp.azurecr.io/confluentinc/cp-server-connect:7.0.1-1.6.8
    init: confluentinc/confluent-init-container:2.2.0-1
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
# ---
# apiVersion: platform.confluent.io/v1beta1
# kind: KsqlDB
# metadata:
#   name: ksqldb
#   namespace: confluent
# spec:
#   replicas: 1
#   image:
#     application: confluentinc/cp-ksqldb-server:7.0.1
#     init: confluentinc/confluent-init-container:2.2.0-1
#   dataVolumeCapacity: 10Gi
---
  apiVersion: platform.confluent.io/v1beta1
  kind: ControlCenter
  metadata:
   name: controlcenter
   namespace: confluent
  spec:
   podTemplate:
    resources:
      limits:
        cpu: 1500m
        memory: 4096Mi
      requests:
        cpu: 500m
        memory: 2096Mi
    tolerations:
      - effect: NoSchedule
        key: app
        value: confluent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: app
              operator: In
              values:
              - confluent
   replicas: 1
   image:
     application: confluentinc/cp-enterprise-control-center:7.0.1
     init: confluentinc/confluent-init-container:2.2.0-1
   dataVolumeCapacity: 100Gi
   dependencies:
     schemaRegistry:
       url: http://schemaregistry.confluent.svc.cluster.local:8081
    #  ksqldb:
    #  - name: ksqldb
    #    url: http://ksqldb.confluent.svc.cluster.local:8088
     connect:
     - name: connect
       url: http://connect.confluent.svc.cluster.local:8083
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  podTemplate:
    resources:
      limits:
        cpu: 1000m
        memory: 3096Mi
      requests:
        cpu: 500m
        memory: 2096Mi
    tolerations:
      - effect: NoSchedule
        key: app
        value: confluent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: app
              operator: In
              values:
              - confluent
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  podTemplate:
    resources:
      limits:
        cpu: 1500m
        memory: 3096Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    tolerations:
      - effect: NoSchedule
        key: app
        value: confluent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: app
              operator: In
              values:
              - confluent
  replicas: 1
  image:
    application: confluentinc/cp-kafka-rest:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1